### ISSUE TITLE
Primeira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G3_ProjetoHigia#20]
Olá Pessoal!

O Grupo 03 irá avaliar o Grupo 04 nessa primeira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Base) da trilha do Moodle, e procurar por "Primeira Avaliação por Pares".

Atenciosamente.

**Comment by ithaloazevedo** [comment]
A avaliação foi realizada e já foi enviada no moodle!
